name = "app"
account_id = "c78fd40c4d7ce735c7d8969d6905fde0"
main = "src/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

workers_dev = true

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "trace"
database_id = "e9b94902-23ff-44a4-bd99-b57cb4185da1"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "SESSIONS"
id = "a9111b5184d7436f90debfb9c3c92bcb"

[triggers]
crons = ["0 20 * * *"]