-- CSHS TRACE demo seed data
-- Generated by scripts/gen-seed.mjs. Do not edit by hand.
PRAGMA foreign_keys = ON;

INSERT INTO users (name, email, password_hash, role, active) VALUES ('System Administrator', 'admin@cshs.edu.ph', 'pbkdf2:100000:3d878dff230d25790f46bc2af060b3e3:ce06a5df70ae6c1386d771441261545fb250798cd7642dd384903fb22e51705c', 'admin', 1);
INSERT INTO users (name, email, password_hash, role, active) VALUES ('Marilou Santos', 'msantos@cshs.edu.ph', 'pbkdf2:100000:e146d32b255649a613f56efe2b6b54a6:32a5f1a497864024f067b46bb9d8cd7b4d529b3b99451ac2d2c14157444d995e', 'teacher', 1);
INSERT INTO users (name, email, password_hash, role, active) VALUES ('Ramon Dela Cruz', 'rdelacruz@cshs.edu.ph', 'pbkdf2:100000:2ba264c67532fb1ce2ae67e60198d99e:913719e91adc6fdebcae408e8c224fff12aff9ea87f7b28116fac752f88dc130', 'teacher', 1);
INSERT INTO users (name, email, password_hash, role, active) VALUES ('Grace Villanueva', 'gvillanueva@cshs.edu.ph', 'pbkdf2:100000:a7f67f612a589a68f9f79ca33f114e23:fe4a41cb7386706ee77b5976174ea3e16aea34d920bd7a90da85f154c18a2a82', 'teacher', 1);
INSERT INTO users (name, email, password_hash, role, active) VALUES ('Edwin Reyes', 'ereyes@cshs.edu.ph', 'pbkdf2:100000:2f00c122387bc02e8c9596e8a7797fc4:74052d7d148387919acf791cd18fa5e5cf82427e19623af02155fca250053a14', 'teacher', 1);
INSERT INTO users (name, email, password_hash, role, active) VALUES ('Liza Bautista', 'lbautista@cshs.edu.ph', 'pbkdf2:100000:6e94c746bb26cbe8fdafd230aa2707d5:0c096e948a39eae9599f68e1f7974bdb53454a1492482e89082f8f9cc09c9123', 'teacher', 1);
INSERT INTO users (name, email, password_hash, role, active) VALUES ('Josefa Aquino', 'jaquino@cshs.edu.ph', 'pbkdf2:100000:e2f6dc593da238fc83be927e5a7bb9d0:04a0389955bd35caeb4ba288d67256da2349d5fd73882e8d1f00a42cb644035c', 'teacher', 1);
INSERT INTO users (name, email, password_hash, role, active) VALUES ('Carlos Mendoza', 'cmendoza@cshs.edu.ph', 'pbkdf2:100000:8f25e019b44ed8d9c3d4fd1624effd0b:8058dd625f9c4a1f8c8a71867ffe7a3982f09f40dd5ccf80147de79c151246ed', 'teacher', 1);
INSERT INTO users (name, email, password_hash, role, active) VALUES ('Teresa Lim', 'tlim@cshs.edu.ph', 'pbkdf2:100000:5703d4e8a7c5298178f2ffaa2fbec62b:477cd0a4becf18c694cf8b61f6271e4660280b2d9c0844282d6bec45e20cc1e6', 'teacher', 1);

INSERT INTO teacher_profiles (user_id, department, subjects, max_weekly_load, notes) VALUES (2, 'English', 'English 8, Literature', 8, '');
INSERT INTO teacher_profiles (user_id, department, subjects, max_weekly_load, notes) VALUES (3, 'Mathematics', 'Algebra, Geometry', 10, '');
INSERT INTO teacher_profiles (user_id, department, subjects, max_weekly_load, notes) VALUES (4, 'Science', 'Biology, Chemistry', 8, '');
INSERT INTO teacher_profiles (user_id, department, subjects, max_weekly_load, notes) VALUES (5, 'Social Studies', 'History, Economics', 10, '');
INSERT INTO teacher_profiles (user_id, department, subjects, max_weekly_load, notes) VALUES (6, 'Filipino', 'Filipino 9, Panitikan', 8, '');
INSERT INTO teacher_profiles (user_id, department, subjects, max_weekly_load, notes) VALUES (7, 'MAPEH', 'PE, Health', 12, '');
INSERT INTO teacher_profiles (user_id, department, subjects, max_weekly_load, notes) VALUES (8, 'Mathematics', 'Trigonometry, Statistics', 10, '');
INSERT INTO teacher_profiles (user_id, department, subjects, max_weekly_load, notes) VALUES (9, 'Science', 'Physics', 8, '');

INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (2, 0, 1, 'English 8', 'Grade 8 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (2, 0, 2, 'English 8', 'Grade 8 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (2, 1, 3, 'Literature', 'Grade 9 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (2, 2, 1, 'English 8', 'Grade 8 - C');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (2, 3, 4, 'Literature', 'Grade 9 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (2, 4, 2, 'English 8', 'Grade 8 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (3, 0, 3, 'Algebra', 'Grade 7 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (3, 1, 1, 'Algebra', 'Grade 7 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (3, 2, 4, 'Geometry', 'Grade 10 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (3, 3, 2, 'Geometry', 'Grade 10 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (3, 4, 1, 'Algebra', 'Grade 7 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (4, 0, 4, 'Biology', 'Grade 10 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (4, 1, 2, 'Biology', 'Grade 10 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (4, 2, 3, 'Chemistry', 'Grade 11 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (4, 3, 1, 'Chemistry', 'Grade 11 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (4, 4, 4, 'Biology', 'Grade 10 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (5, 0, 5, 'History', 'Grade 8 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (5, 1, 4, 'Economics', 'Grade 11 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (5, 2, 5, 'History', 'Grade 9 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (5, 3, 3, 'Economics', 'Grade 11 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (5, 4, 5, 'History', 'Grade 8 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (6, 0, 6, 'Filipino 9', 'Grade 9 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (6, 1, 5, 'Panitikan', 'Grade 10 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (6, 2, 6, 'Filipino 9', 'Grade 9 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (6, 3, 5, 'Panitikan', 'Grade 10 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (6, 4, 6, 'Filipino 9', 'Grade 9 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (7, 0, 7, 'PE', 'Grade 8 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (7, 1, 6, 'Health', 'Grade 8 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (7, 2, 7, 'PE', 'Grade 9 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (7, 3, 6, 'Health', 'Grade 9 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (7, 4, 7, 'PE', 'Grade 8 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (8, 0, 8, 'Trigonometry', 'Grade 12 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (8, 1, 7, 'Statistics', 'Grade 12 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (8, 2, 8, 'Trigonometry', 'Grade 12 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (8, 3, 7, 'Statistics', 'Grade 12 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (8, 4, 8, 'Trigonometry', 'Grade 12 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (9, 0, 2, 'Physics', 'Grade 12 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (9, 1, 8, 'Physics', 'Grade 12 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (9, 2, 2, 'Physics', 'Grade 12 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (9, 3, 8, 'Physics', 'Grade 12 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (9, 4, 2, 'Physics', 'Grade 12 - A');

INSERT INTO availability (teacher_id, date, period, status, source) VALUES (4, '2026-08-21', 2, 'unavailable', 'manual');
INSERT INTO availability (teacher_id, date, period, status, source) VALUES (5, '2026-08-22', 3, 'unavailable', 'manual');
INSERT INTO availability (teacher_id, date, period, status, source) VALUES (7, '2026-08-23', 4, 'unavailable', 'manual');
INSERT INTO availability (teacher_id, date, period, status, source) VALUES (8, '2026-08-21', 5, 'unavailable', 'manual');

INSERT INTO absences (teacher_id, date, period, reason, status, requested_by, reviewed_by, reviewed_at) VALUES (3, '2026-08-21', 1, 'Medical appointment', 'approved', 2, 1, datetime('now'));
INSERT INTO absences (teacher_id, date, period, reason, status, requested_by, reviewed_by, reviewed_at) VALUES (4, '2026-08-22', 4, 'Family emergency', 'approved', 4, 1, datetime('now'));
INSERT INTO absences (teacher_id, date, period, reason, status, requested_by) VALUES (6, '2026-08-23', 2, 'Seminar attendance', 'pending', 6);

INSERT INTO relief_assignments (absence_id, reliever_id, date, period, subject, class_name, status, is_override, created_by) VALUES (1, 8, '2026-08-21', 1, 'Algebra', 'Grade 7 - A', 'assigned', 0, 1);

INSERT INTO notifications (user_id, type, message, link, is_read) VALUES (8, 'relief_assignment', 'You have been assigned to cover Algebra (Grade 7 - A) on 2026-08-21, Period 1.', '/relief', 0);
INSERT INTO notifications (user_id, type, message, link, is_read) VALUES (1, 'absence_approved', 'Ramon Dela Cruz''s absence on 2026-08-21 (Period 1) was approved.', '/requests', 0);
