-- CSHS TRACE demo seed data
-- Generated by scripts/gen-seed.mjs. Do not edit by hand.
PRAGMA foreign_keys = ON;

INSERT INTO users (name, email, password_hash, role, active) VALUES ('System Administrator', 'admin@cshs.edu.ph', 'pbkdf2:100000:3b8b206b669be3648f79a923a8790f8f:2f683cd81bd4aab9119a4fb47c45ccdc365be06e91a8a9fc4e702097b152de6a', 'admin', 1);
INSERT INTO users (name, email, password_hash, role, active) VALUES ('Marilou Santos', 'msantos@cshs.edu.ph', 'pbkdf2:100000:2774ba161729caa0f44fc9d34ddc2e87:08761d95a8ced906d95b808c5bd387655460f3af02c6990bceae96c01312d16e', 'teacher', 1);
INSERT INTO users (name, email, password_hash, role, active) VALUES ('Ramon Dela Cruz', 'rdelacruz@cshs.edu.ph', 'pbkdf2:100000:0d670f3feebdb494fdf194da34599bca:d2b853ba9e0e66d40a4fd1046fb01951e407ef383921bf9f350d67ca636e4cfb', 'teacher', 1);
INSERT INTO users (name, email, password_hash, role, active) VALUES ('Grace Villanueva', 'gvillanueva@cshs.edu.ph', 'pbkdf2:100000:b4a776814d7948a616aa74d8b75e51a8:f5b7ec6ac951d27d49bc52b0ac1ef75fa40506fa223d3ac2ba103e2279498bc5', 'teacher', 1);
INSERT INTO users (name, email, password_hash, role, active) VALUES ('Edwin Reyes', 'ereyes@cshs.edu.ph', 'pbkdf2:100000:13e8e431a90cd7b5e53e05af13a4f4db:88f2c117bac5c78650f06722c30b0dfc23e7f737d85d84816baa67312aa818b5', 'teacher', 1);
INSERT INTO users (name, email, password_hash, role, active) VALUES ('Liza Bautista', 'lbautista@cshs.edu.ph', 'pbkdf2:100000:abd292a78ddbf6aa7077cec9b7db639a:7594ae0defdd64496d90f3e662d9661676c812eab5a6f4b28455855bcee73b27', 'teacher', 1);
INSERT INTO users (name, email, password_hash, role, active) VALUES ('Josefa Aquino', 'jaquino@cshs.edu.ph', 'pbkdf2:100000:16ff4fc563fc1e34c6816dbaaeb88486:64fe7c97f46f4da231571c704084ac987dd7ac6d0d7789729bc6a88d1559c74e', 'teacher', 1);
INSERT INTO users (name, email, password_hash, role, active) VALUES ('Carlos Mendoza', 'cmendoza@cshs.edu.ph', 'pbkdf2:100000:633c9f1c9a3b2fe7d091cfb472344510:ab51f3589d03868ed53fbb8032b192de2170802ae1d3b5d848be917ba9e1d012', 'teacher', 1);
INSERT INTO users (name, email, password_hash, role, active) VALUES ('Teresa Lim', 'tlim@cshs.edu.ph', 'pbkdf2:100000:8ad130604c1f25811d746ed82cd08621:56795406d8d678c9e0308f2070b0daf5605f65a79b516140d116ce88addf488f', 'teacher', 1);

INSERT INTO teacher_profiles (user_id, department, subjects, max_weekly_load, notes) VALUES (2, 'English', 'English 8, Literature', 8, '');
INSERT INTO teacher_profiles (user_id, department, subjects, max_weekly_load, notes) VALUES (3, 'Mathematics', 'Algebra, Geometry', 10, '');
INSERT INTO teacher_profiles (user_id, department, subjects, max_weekly_load, notes) VALUES (4, 'Science', 'Biology, Chemistry', 8, '');
INSERT INTO teacher_profiles (user_id, department, subjects, max_weekly_load, notes) VALUES (5, 'Social Studies', 'History, Economics', 10, '');
INSERT INTO teacher_profiles (user_id, department, subjects, max_weekly_load, notes) VALUES (6, 'Filipino', 'Filipino 9, Panitikan', 8, '');
INSERT INTO teacher_profiles (user_id, department, subjects, max_weekly_load, notes) VALUES (7, 'MAPEH', 'PE, Health', 12, '');
INSERT INTO teacher_profiles (user_id, department, subjects, max_weekly_load, notes) VALUES (8, 'Mathematics', 'Trigonometry, Statistics', 10, '');
INSERT INTO teacher_profiles (user_id, department, subjects, max_weekly_load, notes) VALUES (9, 'Science', 'Physics', 8, '');

INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (2, 0, 1, 'English 8', 'Grade 8 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (2, 0, 2, 'English 8', 'Grade 8 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (2, 1, 3, 'Literature', 'Grade 9 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (2, 2, 1, 'English 8', 'Grade 8 - C');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (2, 3, 4, 'Literature', 'Grade 9 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (2, 4, 2, 'English 8', 'Grade 8 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (3, 0, 3, 'Algebra', 'Grade 7 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (3, 1, 1, 'Algebra', 'Grade 7 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (3, 2, 4, 'Geometry', 'Grade 10 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (3, 3, 2, 'Geometry', 'Grade 10 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (3, 4, 1, 'Algebra', 'Grade 7 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (4, 0, 4, 'Biology', 'Grade 10 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (4, 1, 2, 'Biology', 'Grade 10 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (4, 2, 3, 'Chemistry', 'Grade 11 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (4, 3, 1, 'Chemistry', 'Grade 11 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (4, 4, 4, 'Biology', 'Grade 10 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (5, 0, 5, 'History', 'Grade 8 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (5, 1, 4, 'Economics', 'Grade 11 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (5, 2, 5, 'History', 'Grade 9 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (5, 3, 3, 'Economics', 'Grade 11 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (5, 4, 5, 'History', 'Grade 8 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (6, 0, 6, 'Filipino 9', 'Grade 9 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (6, 1, 5, 'Panitikan', 'Grade 10 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (6, 2, 6, 'Filipino 9', 'Grade 9 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (6, 3, 5, 'Panitikan', 'Grade 10 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (6, 4, 6, 'Filipino 9', 'Grade 9 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (7, 0, 7, 'PE', 'Grade 8 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (7, 1, 6, 'Health', 'Grade 8 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (7, 2, 7, 'PE', 'Grade 9 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (7, 3, 6, 'Health', 'Grade 9 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (7, 4, 7, 'PE', 'Grade 8 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (8, 0, 8, 'Trigonometry', 'Grade 12 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (8, 1, 7, 'Statistics', 'Grade 12 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (8, 2, 8, 'Trigonometry', 'Grade 12 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (8, 3, 7, 'Statistics', 'Grade 12 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (8, 4, 8, 'Trigonometry', 'Grade 12 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (9, 0, 2, 'Physics', 'Grade 12 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (9, 1, 8, 'Physics', 'Grade 12 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (9, 2, 2, 'Physics', 'Grade 12 - A');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (9, 3, 8, 'Physics', 'Grade 12 - B');
INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (9, 4, 2, 'Physics', 'Grade 12 - A');

INSERT INTO availability (teacher_id, date, period, status, source) VALUES (4, '2026-08-21', 2, 'unavailable', 'manual');
INSERT INTO availability (teacher_id, date, period, status, source) VALUES (5, '2026-08-22', 3, 'unavailable', 'manual');
INSERT INTO availability (teacher_id, date, period, status, source) VALUES (7, '2026-08-23', 4, 'unavailable', 'manual');
INSERT INTO availability (teacher_id, date, period, status, source) VALUES (8, '2026-08-21', 5, 'unavailable', 'manual');
INSERT INTO availability (teacher_id, date, period, status, source) VALUES (10, '2026-08-20', 1, 'available', 'manual');
INSERT INTO availability (teacher_id, date, period, status, source) VALUES (11, '2026-08-20', 3, 'available', 'manual');
INSERT INTO availability (teacher_id, date, period, status, source) VALUES (8, '2026-08-20', 2, 'available', 'manual');
INSERT INTO availability (teacher_id, date, period, status, source) VALUES (9, '2026-08-20', 4, 'available', 'manual');

INSERT INTO absences (teacher_id, date, period, reason, status, requested_by, reviewed_by, reviewed_at) VALUES (1, '2026-08-21', 1, 'Medical appointment', 'approved', 2, 1, datetime('now'));
INSERT INTO absences (teacher_id, date, period, reason, status, requested_by, reviewed_by, reviewed_at) VALUES (3, '2026-08-22', 4, 'Family emergency', 'approved', 4, 1, datetime('now'));
INSERT INTO absences (teacher_id, date, period, reason, status, requested_by) VALUES (5, '2026-08-23', 2, 'Seminar attendance', 'pending', 5);

INSERT INTO relief_assignments (absence_id, reliever_id, date, period, subject, class_name, status, is_override, created_by) VALUES (1, 8, '2026-08-21', 1, 'Algebra', 'Grade 7 - A', 'assigned', 0, 1);

INSERT INTO notifications (user_id, type, message, link, is_read) VALUES (8, 'relief_assignment', 'You have been assigned to cover Algebra (Grade 7 - A) on 2026-08-21, Period 1.', '/relief', 0);
INSERT INTO notifications (user_id, type, message, link, is_read) VALUES (1, 'absence_approved', 'Ramon Dela Cruz''s absence on 2026-08-21 (Period 1) was approved.', '/requests', 0);
