// Generates migrations/seed.sql with demo data for CSHS TRACE.
// Run: npm run gen:seed
import { webcrypto } from "node:crypto";
import { writeFileSync } from "node:fs";

const { subtle } = webcrypto;

function hex(bytes) {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

async function hashPassword(password, saltHex) {
  const key = await subtle.importKey(
    "raw",
    new TextEncoder().encode(password),
    "PBKDF2",
    false,
    ["deriveBits"]
  );
  const bits = await subtle.deriveBits(
    {
      name: "PBKDF2",
      salt: Uint8Array.from(Buffer.from(saltHex, "hex")),
      iterations: 100000,
      hash: "SHA-256",
    },
    key,
    256
  );
  return hex(new Uint8Array(bits));
}

function randomHex(bytes = 16) {
  const arr = new Uint8Array(bytes);
  crypto.getRandomValues(arr);
  return hex(arr);
}

async function makeHash(password) {
  const salt = randomHex();
  const hash = await hashPassword(password, salt);
  return `pbkdf2:100000:${salt}:${hash}`;
}

const teachers = [
  { name: "Marilou Santos", email: "msantos@cshs.edu.ph", dept: "English", subjects: "English 8, Literature", maxLoad: 8 },
  { name: "Ramon Dela Cruz", email: "rdelacruz@cshs.edu.ph", dept: "Mathematics", subjects: "Algebra, Geometry", maxLoad: 10 },
  { name: "Grace Villanueva", email: "gvillanueva@cshs.edu.ph", dept: "Science", subjects: "Biology, Chemistry", maxLoad: 8 },
  { name: "Edwin Reyes", email: "ereyes@cshs.edu.ph", dept: "Social Studies", subjects: "History, Economics", maxLoad: 10 },
  { name: "Liza Bautista", email: "lbautista@cshs.edu.ph", dept: "Filipino", subjects: "Filipino 9, Panitikan", maxLoad: 8 },
  { name: "Josefa Aquino", email: "jaquino@cshs.edu.ph", dept: "MAPEH", subjects: "PE, Health", maxLoad: 12 },
  { name: "Carlos Mendoza", email: "cmendoza@cshs.edu.ph", dept: "Mathematics", subjects: "Trigonometry, Statistics", maxLoad: 10 },
  { name: "Teresa Lim", email: "tlim@cshs.edu.ph", dept: "Science", subjects: "Physics", maxLoad: 8 },
];

const weekdayMap = { Mon: 0, Tue: 1, Wed: 2, Thu: 3, Fri: 4 };

// Schedules: [teacherIndex, weekday, period, subject, class]
const schedules = [
  [0, 0, 1, "English 8", "Grade 8 - A"],
  [0, 0, 2, "English 8", "Grade 8 - B"],
  [0, 1, 3, "Literature", "Grade 9 - A"],
  [0, 2, 1, "English 8", "Grade 8 - C"],
  [0, 3, 4, "Literature", "Grade 9 - B"],
  [0, 4, 2, "English 8", "Grade 8 - A"],
  [1, 0, 3, "Algebra", "Grade 7 - A"],
  [1, 1, 1, "Algebra", "Grade 7 - B"],
  [1, 2, 4, "Geometry", "Grade 10 - A"],
  [1, 3, 2, "Geometry", "Grade 10 - B"],
  [1, 4, 1, "Algebra", "Grade 7 - A"],
  [2, 0, 4, "Biology", "Grade 10 - A"],
  [2, 1, 2, "Biology", "Grade 10 - B"],
  [2, 2, 3, "Chemistry", "Grade 11 - A"],
  [2, 3, 1, "Chemistry", "Grade 11 - B"],
  [2, 4, 4, "Biology", "Grade 10 - A"],
  [3, 0, 5, "History", "Grade 8 - A"],
  [3, 1, 4, "Economics", "Grade 11 - A"],
  [3, 2, 5, "History", "Grade 9 - A"],
  [3, 3, 3, "Economics", "Grade 11 - B"],
  [3, 4, 5, "History", "Grade 8 - A"],
  [4, 0, 6, "Filipino 9", "Grade 9 - A"],
  [4, 1, 5, "Panitikan", "Grade 10 - A"],
  [4, 2, 6, "Filipino 9", "Grade 9 - B"],
  [4, 3, 5, "Panitikan", "Grade 10 - B"],
  [4, 4, 6, "Filipino 9", "Grade 9 - A"],
  [5, 0, 7, "PE", "Grade 8 - A"],
  [5, 1, 6, "Health", "Grade 8 - B"],
  [5, 2, 7, "PE", "Grade 9 - A"],
  [5, 3, 6, "Health", "Grade 9 - B"],
  [5, 4, 7, "PE", "Grade 8 - A"],
  [6, 0, 8, "Trigonometry", "Grade 12 - A"],
  [6, 1, 7, "Statistics", "Grade 12 - B"],
  [6, 2, 8, "Trigonometry", "Grade 12 - B"],
  [6, 3, 7, "Statistics", "Grade 12 - A"],
  [6, 4, 8, "Trigonometry", "Grade 12 - A"],
  [7, 0, 2, "Physics", "Grade 12 - A"],
  [7, 1, 8, "Physics", "Grade 12 - B"],
  [7, 2, 2, "Physics", "Grade 12 - A"],
  [7, 3, 8, "Physics", "Grade 12 - B"],
  [7, 4, 2, "Physics", "Grade 12 - A"],
];

function isoDaysAgo(n) {
  const d = new Date();
  d.setUTCDate(d.getUTCDate() + n);
  return d.toISOString().slice(0, 10);
}

async function main() {
  const lines = [];
  lines.push("-- CSHS TRACE demo seed data");
  lines.push("-- Generated by scripts/gen-seed.mjs. Do not edit by hand.");
  lines.push("PRAGMA foreign_keys = ON;");
  lines.push("");

  const adminHash = await makeHash("admin123");
  lines.push(`INSERT INTO users (name, email, password_hash, role, active) VALUES ('System Administrator', 'admin@cshs.edu.ph', '${adminHash}', 'admin', 1);`);

  for (const t of teachers) {
    const hash = await makeHash("teacher123");
    lines.push(`INSERT INTO users (name, email, password_hash, role, active) VALUES ('${t.name}', '${t.email}', '${hash}', 'teacher', 1);`);
  }
  lines.push("");

  // teacher profiles: teacher id = index + 2 (admin is id 1)
  teachers.forEach((t, i) => {
    const userId = i + 2;
    lines.push(
      `INSERT INTO teacher_profiles (user_id, department, subjects, max_weekly_load, notes) VALUES (${userId}, '${t.dept}', '${t.subjects}', ${t.maxLoad}, '');`
    );
  });
  lines.push("");

  for (const [ti, wk, period, subject, cls] of schedules) {
    const userId = ti + 2;
    lines.push(`INSERT INTO schedules (teacher_id, weekday, period, subject, class_name) VALUES (${userId}, ${wk}, ${period}, '${subject}', '${cls}');`);
  }
  lines.push("");

  // Availability: some teachers mark unavailable for specific upcoming days
  const avails = [
    [2, 1, 2, "unavailable"], // Grace unavailable Mon period 2
    [3, 2, 3, "unavailable"], // Edwin unavailable Tue period 3
    [5, 3, 4, "unavailable"], // Liza unavailable Wed period 4
    [6, 1, 5, "unavailable"], // Josefa unavailable Tue period 5
  ];
  for (const [ti, dayOffset, period, status] of avails) {
    const userId = ti + 2;
    lines.push(`INSERT INTO availability (teacher_id, date, period, status, source) VALUES (${userId}, '${isoDaysAgo(dayOffset)}', ${period}, '${status}', 'manual');`);
  }
  lines.push("");

  // Absence: approved absence tomorrow for teacher 3 (Ramon) period 1
  const tomorrow = isoDaysAgo(1);
  lines.push(`INSERT INTO absences (teacher_id, date, period, reason, status, requested_by, reviewed_by, reviewed_at) VALUES (3, '${tomorrow}', 1, 'Medical appointment', 'approved', 2, 1, datetime('now'));`);
  // approved absence day after tomorrow for teacher 4 (Grace) period 4
  const dayAfter = isoDaysAgo(2);
  lines.push(`INSERT INTO absences (teacher_id, date, period, reason, status, requested_by, reviewed_by, reviewed_at) VALUES (4, '${dayAfter}', 4, 'Family emergency', 'approved', 4, 1, datetime('now'));`);
  lines.push(`INSERT INTO absences (teacher_id, date, period, reason, status, requested_by) VALUES (6, '${isoDaysAgo(3)}', 2, 'Seminar attendance', 'pending', 6);`);
  lines.push("");

  // A relief assignment: teacher 8 (Carlos) covers Ramon's absence tomorrow
  lines.push(`INSERT INTO relief_assignments (absence_id, reliever_id, date, period, subject, class_name, status, is_override, created_by) VALUES (1, 8, '${tomorrow}', 1, 'Algebra', 'Grade 7 - A', 'assigned', 0, 1);`);
  lines.push("");

  // Notifications
  lines.push(`INSERT INTO notifications (user_id, type, message, link, is_read) VALUES (8, 'relief_assignment', 'You have been assigned to cover Algebra (Grade 7 - A) on ${tomorrow}, Period 1.', '/relief', 0);`);
  lines.push(`INSERT INTO notifications (user_id, type, message, link, is_read) VALUES (1, 'absence_approved', 'Ramon Dela Cruz''s absence on ${tomorrow} (Period 1) was approved.', '/requests', 0);`);

  writeFileSync(new URL("../migrations/seed.sql", import.meta.url), lines.join("\n") + "\n");
  console.log("seed.sql generated");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});